# RUN CONTROL PARAMETERS
em_default_params = {
    "comment_header_1": "=========================================================",
    "comment_header_2": "ENERGY MINIMIZATION FOR MARTINI COARSE-GRAINED SYSTEMS",
    "comment_header_3": "=========================================================",
    # --- Run Control ---
    "comment_run_control": "--- Run Control ---",
    "integrator": "steep",
    "comment_integrator": "Steepest descent energy minimization",
    "nsteps": 5000,
    "emtol": 10.0,
    "emstep": 0.01,
    # --- Neighbor Searching ---
    "comment_neighbor_searching": "--- Neighbor Searching ---",
    "cutoff-scheme": "Verlet",
    "nstlist": 10,
    "comment_nstlist": "Update neighbor list every 10 steps",
    "ns_type": "grid",
    "pbc": "xyz",
    "verlet-buffer-tolerance": 0.005,
    # --- Electrostatics & vdW (MARTINI STANDARD) ---
    "comment_electrostatics_vdw": "--- Electrostatics & vdW (MARTINI STANDARD) ---",
    "comment_electrostatics_vdw_note": "These settings are critical for Martini accuracy.",
    "coulombtype": "Reaction-Field",
    "rcoulomb": 1.1,
    "epsilon_r": 15,
    "comment_epsilon_r": "Dielectric constant (15 for standard Martini water)",
    "vdw_type": "Cut-off",
    "vdw-modifier": "Potential-shift-verlet",
    "rvdw": 1.1,
}

npt_default_params = {
    "comment_header_1": "=========================================================",
    "comment_header_2": "NPT EQUILIBRATION FOR MARTINI COARSE-GRAINED SYSTEMS",
    "comment_header_3": "=========================================================",
    # --- Run Control ---
    "comment_run_control": "--- Run Control ---",
    "integrator": "md",
    "tinit": 0.0,
    "dt": 0.020,
    "comment_dt": "20 fs time step (standard for Martini)",
    "nsteps": 50000,
    "comment_nsteps": "1 ns total (adjust as needed)",
    "comm-mode": "Linear",
    "comment_comm-mode": "Remove center of mass translation",
    "nstcomm": 100,
    # --- Output Control ---
    "comment_output_control": "--- Output Control ---",
    "nstxout": 5000,
    "comment_nstxout": "Save coordinates every 100 ps",
    "nstvout": 5000,
    "comment_nstvout": "Save velocities every 100 ps",
    "nstfout": 0,
    "nstlog": 1000,
    "comment_nstlog": "Update log file every 20 ps",
    "nstenergy": 1000,
    "comment_nstenergy": "Save energy every 20 ps",
    "nstxout-compressed": 1000,
    "comment_nstxout-compressed": "Save compressed trajectory (xtc) every 20 ps",
    "compressed-x-precision": 1000,
    # --- Neighbor Searching ---
    "comment_neighbor_searching": "--- Neighbor Searching ---",
    "cutoff-scheme": "Verlet",
    "nstlist": 20,
    "comment_nstlist": "Update neighbor list every 20 steps",
    "ns_type": "grid",
    "pbc": "xyz",
    "verlet-buffer-tolerance": 0.005,
    # --- Electrostatics & vdW (MARTINI STANDARD) ---
    "comment_electrostatics_vdw": "--- Electrostatics & vdW (MARTINI STANDARD) ---",
    "comment_electrostatics_vdw_note": "These settings are critical for Martini accuracy.",
    "coulombtype": "Reaction-Field",
    "rcoulomb": 1.1,
    "epsilon_r": 15,
    "comment_epsilon_r": "Dielectric constant (15 for standard Martini water)",
    "vdw_type": "Cut-off",
    "vdw-modifier": "Potential-shift-verlet",
    "rvdw": 1.1,
    # --- Temperature Coupling ---
    "comment_temperature_coupling": "--- Temperature Coupling ---",
    "tcoupl": "V-rescale",
    "comment_tcoupl": "Reliable thermostat",
    "tc-grps": "System",
    "comment_tc-grps": "Define your groups here!",
    "tau_t": 1.0,
    "comment_tau_t": "Time constant (ps)",
    "ref_t": 310,
    "comment_ref_t": "Reference temperature (K)",
    # --- Pressure Coupling ---
    "comment_pressure_coupling": "--- Pressure Coupling ---",
    "pcoupl": "C-rescale",
    "comment_pcoupl": "Berendsen is stable for equilibration",
    "pcoupltype": "semiisotropic",
    "comment_pcoupltype": "use 'isotropic' for protein-in-water, 'semiisotropic' for membranes",
    "tau_p": 5.0,
    "comment_tau_p": "Time constant (ps)",
    "compressibility": "3e-4  3e-4",
    "comment_compressibility": "Compressibility (bar^-1) - typically 3e-4 for Martini",
    "ref_p": "1.0   1.0",
    "comment_ref_p": "Reference pressure (bar) (xy and z for semiisotropic)",
    "refcoord_scaling": "com",
    # --- Velocity Generation ---
    "comment_velocity_generation": "--- Velocity Generation ---",
    "gen_vel": "yes",
    "comment_gen_vel": "Generate velocities if starting fresh",
    "gen_temp": 310,
    "gen_seed": -1,
    "comment_gen_seed": "Random seed",
    # --- Constraints ---
    "comment_constraints_header": "--- Constraints ---",
    "constraints": "none",
    "comment_constraints_note": "Martini beads are usually not constrained",
    "constraint_algorithm": "Lincs",
}

md_prod_default_params = {
    "comment_header_1": "=========================================================",
    "comment_header_2": "STANDARD MD INPUT OPTIONS FOR MARTINI 3.x",
    "comment_header_3": "=========================================================",
    "comment_note_1": "Updated 20/12/2024 by Kasper B. Pedersen",
    "comment_note_2": "For use with GROMACS 5",
    "comment_note_3": "Ref: D.H. de Jong et al., Martini straight: boosting performance...",
    # --- Run Control ---
    "comment_run_control": "--- Run Control ---",
    "integrator": "md",
    "dt": 0.002,
    "comment_dt": "Timestep in ps (Note: 0.002 ps is 2 fs; Martini typically uses 20-30 fs)",
    "nsteps": 500000000,
    "comment_nsteps": "1 us total duration",
    # --- Output Control ---
    "comment_output_control": "--- Output Control ---",
    "nstxout": 0,
    "nstvout": 0,
    "nstfout": 0,
    "nstlog": 25000,
    "comment_nstlog": "Update log file every 0.5 ns",
    "nstenergy": 25000,
    "comment_nstenergy": "Save energy every 0.5 ns",
    "nstxout-compressed": 50000,
    "comment_nstxout-compressed": "Save compressed trajectory (xtc) every 1 ns",
    "compressed-x-precision": 100,
    "compressed-x-grps": "",
    "energygrps": "System",
    # --- Neighbor Searching ---
    "comment_neighbor_searching": "--- Neighbor Searching ---",
    "cutoff-scheme": "Verlet",
    "nstlist": 20,
    "nsttcouple": 20,
    "nstpcouple": 20,
    "rlist": 2.0,
    "comment_rlist": "Should be at least 1.35 nm for Martini",
    "verlet-buffer-tolerance": -1,
    "comment_verlet-buffer-tolerance": "Disabled to avoid pressure oscillations",
    "ns_type": "grid",
    "pbc": "xyz",
    # --- Electrostatics & vdW (MARTINI STANDARD) ---
    "comment_electrostatics_vdw": "--- Electrostatics & vdW (MARTINI STANDARD) ---",
    "comment_coulomb_note": "Reaction-field gives slightly better properties for Martini",
    "coulombtype": "reaction-field",
    "rcoulomb": 1.1,
    "epsilon_r": 15,
    "comment_epsilon_r": "15 for standard Martini water; 2.5 for polarizable water",
    "epsilon_rf": 0,
    "vdw_type": "cutoff",
    "vdw-modifier": "Potential-shift-verlet",
    "rvdw": 1.1,
    # --- Temperature Coupling ---
    "comment_temperature_coupling": "--- Temperature Coupling ---",
    "tcoupl": "v-rescale",
    "tc-grps": "System",
    "tau_t": 1.0,
    "ref_t": 310,
    # --- Pressure Coupling ---
    "comment_pressure_coupling": "--- Pressure Coupling ---",
    "comment_pcoupl_note": "C-rescale is recommended for stability and sampling",
    "pcoupl": "c-rescale",
    "pcoupltype": "semiisotropic",
    "tau_p": 4.0,
    "ref_p": "1.0 1.0",
    "compressibility": "3e-4 3e-4",
    "refcoord_scaling": "all",
    # --- Velocity Generation ---
    "comment_velocity_generation": "--- Velocity Generation ---",
    "gen_vel": "no",
    "gen_temp": 310,
    "gen_seed": -1,
}
