"""
Polymer SMILES to PDB Writer Module

This module provides a high-level interface for converting polymer SMILES strings
directly to PDB (Protein Data Bank) format files containing optimized 3D structures.

The PSMILES2PDBWritter class encapsulates the complete workflow:
1. Parse polymer SMILES (pSMILES) strings
2. Create polymer molecules (homopolymer or copolymer)
3. Generate 3D coordinates with force field optimization
4. Write to PDB file format

This is the primary user-facing API for polymer structure generation.

Example:
    >>> writter = PSMILES2PDBWritter(pattern="alt")
    >>> writter.process(["*CCO*", "*CCN*"], dp=10)
    >>> writter.write("output.pdb")
"""

from utils import (
    create_polymer_mol_co,
    create_polymer_mol_homo,
    gen_pdb_conformer,
    write_pdb
)

class PSMILES2PDBWritter:
    """
    A writer class for converting polymer SMILES strings to PDB files.
    
    This class manages the conversion pipeline from polymer SMILES notation to fully
    optimized 3D PDB structures. It supports both homopolymers and copolymers with
    different polymerization patterns.
    
    Attributes:
        pattern (str): The polymerization pattern ("alt", "block", or "random").
        pdb_content (str|None): The generated PDB content. None until process() is called.
    """

    def __init__(self,
                 pattern: str = "alt"):
        """
        Initialize the PSMILES2PDBWritter with a polymerization pattern.
        
        Args:
            pattern (str, optional): Polymerization pattern for copolymers:
                - "alt" (default): Alternating pattern - strictly alternates between monomers
                - "block": Block pattern - first half is monomer 1, second half is monomer 2
                - "random": Random pattern - randomly selects from the two monomers
        
        Raises:
            ValueError: If pattern is not one of the allowed values.
        
        Example:
            >>> writter = PSMILES2PDBWritter(pattern="alt")
            >>> writter_block = PSMILES2PDBWritter(pattern="block")
        """
        ALLOWED_PATTERNS = ["alt", "block", "random"]
        if pattern not in ALLOWED_PATTERNS:
            raise ValueError(f"The pattern should be one of {ALLOWED_PATTERNS}. Passed {pattern}")
        self.pattern = pattern
        self.pdb_content = None

    
    def process(self, data: list[str] | str, dp: int = 10):
        """
        Process polymer SMILES data and generate a 3D molecular structure.
        
        This method creates a polymer molecule from either:
        - A single polymer SMILES string (creates a homopolymer)
        - A list of two polymer SMILES strings (creates a copolymer)
        
        The molecule is then embedded in 3D space with force field optimization.
        The result is stored in self.pdb_content for later writing.
        
        Args:
            data (list[str] | str): 
                - str: A single polymer SMILES string for homopolymer creation
                  Example: "*CCO*" for ethylene oxide
                - list[str]: Exactly 2 polymer SMILES strings for copolymer creation
                  Example: ["*CCO*", "*CCN*"] for alternating copolymer
            dp (int, optional): Degree of polymerization (number of monomer units).
                               Defaults to 10.
        
        Raises:
            ValueError: If data type is neither str nor list.
            AssertionError: If copolymer data doesn't contain exactly 2 monomers.
            ValueError: If 3D structure generation fails (from gen_pdb_conformer).
        
        Side Effects:
            - Generates 3D structure using ETKDG algorithm
            - Optimizes structure with force field (MMFF94 or UFF)
            - Prints progress messages (conformer generation, optimization info)
        
        Example:
            >>> writter = PSMILES2PDBWritter()
            >>> writter.process("*CCO*", dp=5)  # Homopolymer
            >>> writter.process(["*CCO*", "*CCN*"], dp=8)  # Copolymer
        
        Note:
            This method must be called before write() to generate the structure.
        """
        if type(data) == list:
            polymer_mol = create_polymer_mol_co(data, dp, pattern=self.pattern)
        elif type(data) == str:
            polymer_mol = create_polymer_mol_homo(data, dp)
        else:
            raise ValueError("The datatype has to be one of [list, string]. Unknown datatype recieved.")
    
        self.pdb_content = gen_pdb_conformer(polymer_mol)

    def write(self, filepath: str):
        """
        Write the generated PDB structure to a file.
        
        This method writes the PDB content (generated by process()) to the specified file.
        The PDB file will include standard format headers and terminators.
        
        Args:
            filepath (str): Output file path. Must:
                           - Have a .pdb extension
                           - Have a parent directory that exists
                           Example: "results/my_polymer.pdb" or "output.pdb"
        
        Raises:
            ValueError: If process() hasn't been called yet (no PDB content).
            ValueError: If filepath doesn't have .pdb extension.
            AssertionError: If parent directory doesn't exist.
        
        Side Effects:
            - Creates or overwrites file at the specified filepath
            - Appends PDB terminators (TER and END records)
        
        Example:
            >>> writter = PSMILES2PDBWritter()
            >>> writter.process("*CCO*", dp=10)
            >>> writter.write("polymer_structure.pdb")
        
        Note:
            - Parent directory must exist beforehand
            - Overwrite existing files without warning
            - process() must be called before this method
        """
        if self.pdb_content is None:
            raise ValueError("No PDB content to write. Please run process() first.")
        write_pdb(self.pdb_content, filepath)




if __name__ == "__main__":
    writter = PSMILES2PDBWritter()
    writter.process(["*OCC(=O)*", "*C(C)C(=O)O*"], 10)
    writter.write("PEG-b-PLA_10_test.pdb")
