#!/usr/bin/env python3
"""
Quick Reference Guide for Polymer Training and Sampling
========================================================

This script provides quick examples and common usage patterns.
"""

def print_usage_examples():
    """Print comprehensive usage examples."""
    
    print("🚀 Polymer Training and Sampling Runner - Quick Reference")
    print("=" * 60)
    print()
    
    print("📚 TRAINING EXAMPLES:")
    print("-" * 20)
    print("# Basic training with default config")
    print("python src/runner.py train --model gru")
    print()
    print("# Training with custom parameters")
    print("python src/runner.py train --model transformer --epochs 50 --batch-size 64 --learning-rate 0.001")
    print()
    print("# Training with W&B logging")
    print("python src/runner.py train --model lstm --wandb --wandb-project my-polymer-project")
    print()
    print("# Training with custom config file")
    print("python src/runner.py train --model vae --config my_custom_config.yaml")
    print()
    
    print("🧪 SAMPLING EXAMPLES:")
    print("-" * 18)
    print("# Sample from latest experiment (auto-detects best checkpoint)")
    print("python src/runner.py sample --experiment experiments/gru_20240806_123456")
    print()
    print("# Sample with custom parameters")
    print("python src/runner.py sample --experiment experiments/transformer_20240806_123456 \\")
    print("    --num-sequences 50 --max-length 150 --temperature 0.8")
    print()
    print("# Sample from specific checkpoint")
    print("python src/runner.py sample --checkpoint checkpoints/best_model.pth --model transformer")
    print()
    print("# Sample with different decoding strategy")
    print("python src/runner.py sample --experiment experiments/lstm_20240806_123456 \\")
    print("    --strategy top_p --top-p 0.9")
    print()
    
    print("🔍 UTILITY EXAMPLES:")
    print("-" * 17)
    print("# List all experiments")
    print("python src/runner.py list")
    print()
    print("# Show model configuration")
    print("python src/runner.py show-config --model gru --mode train")
    print("python src/runner.py show-config --model transformer --mode sample")
    print()
    
    print("⚙️  AVAILABLE MODELS:")
    print("-" * 17)
    print("• gru           - Gated Recurrent Unit")
    print("• lstm          - Long Short-Term Memory")
    print("• transformer   - Transformer Architecture")
    print("• vae           - Variational Autoencoder")
    print("• tcn           - Temporal Convolutional Network")
    print("• mamba         - Mamba State Space Model")
    print()
    
    print("📁 DIRECTORY STRUCTURE:")
    print("-" * 21)
    print("experiments/")
    print("├── gru_20240806_123456/")
    print("│   ├── checkpoints/")
    print("│   │   ├── best_model.pth")
    print("│   │   └── final_model.pth")
    print("│   ├── logs/")
    print("│   │   └── training.log")
    print("│   ├── config/")
    print("│   │   └── model_config.json")
    print("│   └── results/")
    print("│       ├── training_history.json")
    print("│       └── generated_molecules.json")
    print("└── transformer_20240806_234567/")
    print("    └── ...")
    print()
    
    print("🔧 CONFIGURATION:")
    print("-" * 14)
    print("config/")
    print("├── trainer/")
    print("│   ├── base_config.yaml")
    print("│   ├── gru_config.yaml")
    print("│   ├── lstm_config.yaml")
    print("│   ├── transformer_config.yaml")
    print("│   ├── vae_config.yaml")
    print("│   └── tcn_config.yaml")
    print("└── sampler/")
    print("    ├── base_config.yaml")
    print("    ├── gru_config.yaml")
    print("    ├── lstm_config.yaml")
    print("    ├── transformer_config.yaml")
    print("    ├── vae_config.yaml")
    print("    └── tcn_config.yaml")
    print()
    
    print("💡 TIPS:")
    print("-" * 6)
    print("• Use 'python src/runner.py list' to see all your experiments")
    print("• Experiment directories are automatically timestamped")
    print("• Best checkpoints are automatically selected during sampling")
    print("• All training logs and results are saved in structured directories")
    print("• Use custom configs to override default parameters")
    print("• Enable W&B logging for advanced experiment tracking")
    print()


if __name__ == "__main__":
    print_usage_examples()
